name: pub_proxy_server
version: 0.1.0
author: Alexandre Maurel <alexandre.maurel@gmail.com>
description: Private pub and proxy server.
homepage: https://github.com/amaurel/pub_proxy_server
dependencies:
  crypto: 0.9.0
  http_server: 0.9.1
  logging: 0.9.1+1
  path: 1.0.0
  route: 0.4.6
  route_hierarchical: 0.4.14
  yaml: 0.9.0
dev_dependencies:
  unittest: 0.9.3
