name: pub_proxy_server
author: Alexandre Maurel (alexandre.maurel@gmail.com)
version: 0.0.1
description: Private pub and proxy server.
dependencies:
  http_server: 0.9.1
  logging: 0.9.1+1
  path: 1.0.0
  route: 0.4.6
  route_hierarchical: 0.4.14
